set -g mouse on
set -g history-limit 10000

# status bar
set -g status-position top
set -g status-interval 5
set -g status-left '#S '
set -g status-right '%Y-%m-%d %H:%M'

# nicer window labels
setw -g window-status-format ' #I:#W '
setw -g window-status-current-format ' #I:#W* '

# Vim-like splits
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Vim-like pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-like pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Windows = tabs
bind t new-window -c "#{pane_current_path}"
bind n next-window
bind p previous-window

# Move current window/tab left and right
bind < swap-window -t -1\; select-window -t -1
bind > swap-window -t +1\; select-window -t +1

# Rename current window/tab
bind r command-prompt -I "#W" "rename-window '%%'"

# Kill pane / window
bind x kill-pane
bind X kill-window
